# Generated by Django 5.0.6 on 2024-06-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloginformation",
            name="comment",
            field=models.TextField(default="默认评论"),
        ),
        migrations.AddField(
            model_name="bloginformation",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
