# Generated by Django 5.0.7 on 2024-07-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_bloginformation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginformation',
            name='author',
            field=models.CharField(default='Cs', max_length=100),
        ),
    ]
