# Generated by Django 5.1 on 2024-08-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_viewrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationcode',
            old_name='code',
            new_name='code_register',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='code_reset',
            field=models.CharField(default='dsmngE', max_length=6),
        ),
    ]
